name: helloworld
description: A new Flutter project.

version: 1.0.3+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_polyline_points: ^2.0.0
  http: ^1.2.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  shared_preferences: ^2.2.3
  image_picker: ^1.0.8
  carousel_slider: ^4.2.1
  flutter_map_cancellable_tile_provider: ^2.0.0
  provider: ^6.1.2
  geolocator: ^11.1.0
  screenshot: ^2.5.0
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: "^0.9.2" 
  flutter_app_name: ^0.1.0

# flutter pub run flutter_app_name
flutter_app_name:
  name: "Travel Tales"
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true  
  ios: true  
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/icon.png"  
  adaptive_icon_foreground: "assets/icon.png" 

flutter:
  uses-material-design: true
  assets: 
    - assets/
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
